### PR TITLE
Added small piece to reach the tactile button from the back shell

### PR DESCRIPTION
**Pull request by MasonStooksbury**
Adding a small piece to reach the button from the back shell. Fits great, works well, and doesn't fall out
button
IMG20231221114136
IMG20231221114114

### CODE REVIEW

**Comment by Polprzewodnikowy** [comment]
Is this button designed for B3FS-1050 tactile switch? I don't think it will fit with the part I listed in the BOM. 
image

**Comment by Polprzewodnikowy** [comment]
I know that some early boards have different button due to my error - not listing correct part in the BOM.

**Comment by MasonStooksbury** [comment]
Ah, I didn't realize it'd changed. The model I have has the older version, then. Similar to one of these
Screenshot_2023-12-21-14-59-07-71_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Polprzewodnikowy** [comment]
Is it a 3.1 mm or 4.3 mm model?
image

**Comment by MasonStooksbury** [comment]
> Is it a 3.1 mm or 4.3 mm model? image

The 4.3mm model

**Comment by Polprzewodnikowy** [comment]
I can merge this PR if you add `_b3fs-101x` suffix to the file name.

**Comment by MasonStooksbury** [comment]
Yeah, if you think it'll still be helpful despite the new BOM, I'll make that change and get it pushed.

I'd also like to work on a version for the current switch once the board comes in.

Thanks!

**Pull request merged**
